#!/bin/bash


SUBNET="10.0.2"


for i in {0..255}; do
    
    ping -c 1 -W 1 $SUBNET.$i > /dev/null 2>&1

    
    if [ $? -eq 0 ]; then
        echo "Server $SUBNET.$i is up and running"
    else
        echo "Server $SUBNET.$i is unreachable"
    fi
done
