#!/bin/bash


SUBNET="10.0.2"


for i in {0..255}; do
    # Ping the current IP address
    ping -c 1 -W 1 $SUBNET.$i > /dev/null 2>&1

    # Check the exit status of the ping command
    if [ $? -eq 0 ]; then
        echo "Server $SUBNET.$i is up and running"
    else
        echo "Server $SUBNET.$i is unreachable"
    fi
done
